language: java

services:
  - postgresql

before_script:
  - psql -c 'create database trucking_industry;' -U postgres

addons:
  sonarcloud:
    organization: "alexandernesterov"
    token:
      secure: d108dab4cce1796654ee55b7e6d6229ac6967a5c

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
